/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package matrix.math;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        System.out.println("Tests are running. Hello from it's guts :)");
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
